### ISSUE TITLE
Desktop/VR Toggle

### ISSUE THREAD

**Issue by twday** [openleap/aframe-leap-hands#17] opened 2017-03-10 13:53 UTC
Aframe hands automatically assumes you are using VR but doesn't provide a way to switch to Desktop mode.

I also noticed in your Leap-System, the VR flag is defined in the schema, but then not used beyond that.

Are you planning on implementing this toggle functionality?

Cheers,
Tom

**Comment by donmccurdy** [comment] 2017-03-10 15:20
@tomday  the `vr` flag is used, a bit sneakily, here: https://github.com/openleap/aframe-leap-hands/blob/master/src/leap-system.js#L39

So you can switch modes with:

```html
<a-scene leap="vr: false;">
  <!-- ... -->
</a-scene>
```

I should probably document this. :)

**Comment by twday** [comment] 2017-03-10 15:38
I've tried doing `<a-scene leap="vr: false;"></a-scene>` but when I log it to the console using `document.querySelector('a-scene').Systems["leap"]` it still says true, and makes no difference to the actual rendered hands

**Comment by donmccurdy** [comment] 2017-03-10 15:52
Hm thanks, seems to be a bug then. Will take a look later.

**Comment by donmccurdy** [comment] 2017-03-17 03:28
I haven't been able to reproduce this — for `sceneEl.systems.leap.data.vr` I get `false` when configured as above. Do you have an example you can share?

One other note is that A-Frame systems can't be changed after they're initialized, so `setAttribute('leap', {vr: false})` won't work. This might have implications for JS frameworks, if you're using any.

**Comment by donmccurdy** [comment] 2017-03-31 16:15
Closing this for now, I'm glad to look into it more if you can help me reproduce the problem.

If it's an issue with A-Frame systems not supporting updates, I'm hoping that will be fixed in A-Frame v0.6.0 or v0.7.0.

**Closed as completed by donmccurdy** 2017-03-31 16:15 UTC
